version: '3.5'
services:
  redis:
    image: shareai/redis:x86
    restart: always
    container_name: "redis"
    command: sh -c "redis-server --maxmemory 40mb --maxmemory-policy allkeys-lru --save \"\" --appendonly no --dbfilename \"\""
    #ports:
    #  - 6379:6379
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "10"
  etcd:
    container_name: milvus-etcd
    image: quay.io/coreos/etcd:v3.5.0
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/etcd:/etcd
    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd
  labelstudio:
    container_name: labelstudio
    image: heartexlabs/label-studio:v1.5.0
    ports:
      - "8080:8080"
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/labelstudio-data:/label-studio/data
  minio:
    container_name: milvus-minio
    image: minio/minio:RELEASE.2020-12-03T00-03-10Z
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/minio:/minio_data
    command: minio server /minio_data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  milvus:
    container_name: milvus-standalone
    image: milvusdb/milvus:v2.0.2
    command: ["milvus", "run", "standalone"]
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/milvus:/var/lib/milvus
    ports:
      - "19530:19530"
    depends_on:
      - "etcd"
      - "minio"
  detector:
    container_name: "detector"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "10"
    #image: python:3.8
    #image: huggingface/transformers-pytorch-cpu:4.18.0
    image: shareai/laptop_monitor:x86    
    build:
      context: ./src
      dockerfile: Dockerfile.x86

    restart: always
    ports: 
      - 5901:5901
      - 8000:8080
      - 3000:3000
      - 9000:9000
    env_file:
      - ~/.sharpai/token.env
      - .env
    environment:
      TIMEZONE_OFFSET: ${TIMEZONE_OFFSET}
      IMAGE_DIR: "/opt/nvr/detector/images"
    volumes:
      - ./videos:/opt/nvr/videos
      - ~/.sharpai/device_id:/dev/ro_serialno
      - ~/.sharpai/group_id:/data/usr/com.deep.workai/cache/groupid.txt
      - ./images:/opt/nvr/detector/images
      - ./src/detector_cpu.py:/app/detector.py
      - ./src/LabelStudioClient.py:/app/LabelStudioClient.py
      - ./src/requirements.txt:/app/requirements.txt
